### ISSUE TITLE
Usability Improvements

### ISSUE THREAD

**Issue by gwwatkin** [latticesurgery-com/web-ui#10]
- [x] Loading spinner and disable button after submitting, until response #11 
- [x] Show error responses (maybe using AppState?) Particularly timeouts #20 #22 
- [x] Get compilation text to show
- [x] Add slice number and bounds to Next and Prev #12 
- [x] Moved to #15

**Comment by gwwatkin** [comment]
Split #15 to a separate issue. Since our project is very research-centric and there are many things to do already, we should evaluate carefully our approach to mobile.

**Comment by gwwatkin** [comment]
And plan it carefully. We need to understand first what our mobile users expect to do with the app.

**Comment by Keelando** [comment]
@gwwatkin Am figuring out the compilation text toggle switch component but I have noticed that the compilation text is not being returned in the Axios request response object. Perhaps there is something to change on the lamda?

Compilation text comes up as undefined when I console.log the request response.

I can have a closer look on Saturday.
